Initial Clone - needs updated
Help from Patreon
NerdyRodent
3:39 AM
Reduce the num_workers in instant-nsr-pl/datasets/ortho.py

    def general_loader(self, dataset, batch_size):
        sampler = None
        return DataLoader(
            dataset,
            num_workers=os.cpu_count(), # set it to a smaller one
            batch_size=batch_size,
            pin_memory=True,
            sampler=sampler
        )

    subprocess.CalledProcessError: Command ‘[where, cl]‘ returned non-zero exit status 1

You need to download Visual Studio on your windows, and then add the path of the folder that contains cl.exe to Windows PATH Environment Variable. For example:

C:\XXX\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64

Load Earlier Messages